### ISSUE TITLE
Upgrade to Astro v4

### ISSUE THREAD

**Issue by BuckyBuck135** [cedar-studios/Intermediate-Astro-Kit-LESS#1]
Hello,
Astro has recently released their v4 version, but this template is still running on v3.

# Upgrade Astro and official integrations together
npx @astrojs/upgrade

I have upgraded on my local environment to test it, and everything runs smoothly. There is one warning, as follows:

17:50:10 [WARN] The injected route "/admin" by netlify-cms specifies the entry point with the "entryPoint" property. This property is deprecated, please use "entrypoint" instead.

However, I was not able to locate any file using the entryPoint property. Here is the Astro doc for this particular change: https://docs.astro.build/en/guides/upgrade-to/v4/#renamed-entrypoint-integrations-api

Wondering if the maintainer of this template could upgrade? 
Thank you, and have a niceday.

**Comment by rglanz** [comment]
Yeah, it looks like that parameter is in the `astro-netlify-cms` package.

I opened [an issue](https://github.com/delucis/astro-netlify-cms/issues/86) in their repo, so hopefully they address it soon.

I'm updating Astro to v4 in this repo and will close this issue for now as the warning isn't breaking.

**Comment by cedar-studios** [comment]
Yeah, it looks like that parameter is in the astro-netlify-cms package.

I opened https://github.com/delucis/astro-netlify-cms/issues/86 in their repo, so hopefully they address it soon.

I'm updating Astro to v4 in this repo and will close this issue for now as the warning isn't breaking.
